Add tutorial for implementing shopping cart
Genez-io/genez-io.github.io pull request #32
Opened 2023-11-16 16:38 UTC by andreia-oca

2023-11-16 16:59 UTC, andreia-oca commented
A live preview is available at 
https://gray-just-nightingale.dev.app.genez.io/blog/how-to-implement-a-shopping-cart-feature-using-typescript-redis-and-react/

Feel free to leave comments and improvements in the PR.

2023-11-17 08:07 UTC, costinsin commented on content/posts/implement_shopping_cart.md
> +Redis is an open-source, in-memory database that store key, values pairs. Redis is a highly versatile and performant database system. One of Redis's key features is its speed, as it primarily operate
```suggestion
Redis is an open-source, in-memory database that stores key, values pairs. Redis is a highly versatile and performant database system. One of Redis's key features is its speed, as it primarily operates in-memory, enabling rapid data access. It is widely used for caching, real-time analytics, message brokering, and other applications where low-latency and high-throughput data storage and retrieval are crucial. Redis also provides persistence options, allowing data to be saved to disk for durability. Its simplicity, efficiency, and support for advanced data structures make Redis a popular choice for applications requiring fast and scalable data storage and retrieval.
```

2023-11-17 08:16 UTC, costinsin commented on content/posts/implement_shopping_cart.md
> +Each button should have a its own loading state to indicate that the request is being processed.
A determiner cannot be combined with a possessive pronoun. Did you mean simply 'a' or 'its'?

2023-11-17 08:17 UTC, costinsin commented on content/posts/implement_shopping_cart.md
> +The codebase for this tutorial is open-source and you can find it on the [GitHub repository](https://github.com/genez-io/genezio-examples/tree/main/typescript/shopping-cart).
```suggestion
The codebase for this tutorial is open-source, and you can find it on the [GitHub repository](https://github.com/genez-io/genezio-examples/tree/main/typescript/shopping-cart).
```

2023-11-17 08:42 UTC, costinsin requested changes
I felt like the frontend part is a little bit rushed and assumes that the user knows what's a React application. Maybe you can leave a link to the code before the section starts and state that if they are ever lost they can anytime check the code or copy it directly.

2023-11-17 08:42 UTC, costinsin commented on content/posts/implement_shopping_cart.md
> +Later on, `genezio` come in handy to deploy and host your web applications in the cloud.
Do you mean `genezio will come in handy`?

2023-11-17 08:42 UTC, costinsin commented on content/posts/implement_shopping_cart.md
> +Your terminal should similar to the following output:
```suggestion
Your terminal should look similar to the following output:
```

2023-11-17 08:42 UTC, costinsin commented on content/posts/implement_shopping_cart.md
> +Now that you have a template to start from, fire up your favorite code editor and open project's directory.
```suggestion
Now that you have a template to start from, fire up your favorite code editor and open the project's directory.
```

2023-11-17 08:42 UTC, costinsin commented on content/posts/implement_shopping_cart.md
> +After adding the Upstash Redis integration, copy the environment variable from the `.env` section. Go back to your `server` directory, create a new file called `.env` and paste the contents there.
I think somebody might think that they should copy the *** star output and paste it into the `.env` file. You should mention that they should explicitly use the copy button to disclose their tokens.

2023-11-17 08:42 UTC, costinsin commented on content/posts/implement_shopping_cart.md
> +From the genezio dashboard you can sent request to your backend classes and see the response.
```suggestion
From the genezio dashboard you can send requests to your backend classes and see the responses.
```

2023-11-17 08:42 UTC, costinsin commented on content/posts/implement_shopping_cart.md
> +You'll also need 2 more methods in the backend source code - a method to remove only an item from the cart and a method to delete the entire cart.
```suggestion
 You'll also need 2 more methods in the backend source code - a method to remove only one item from the cart and a method to delete the entire cart.
```

2023-11-17 08:42 UTC, costinsin commented on content/posts/implement_shopping_cart.md
> +Before deploying your application, you can change the randomly-assigned subdomain to something more meaningly for your application.
```suggestion
Before deploying your application, you can change the randomly-assigned subdomain to something more meaningful for your application.
```

2023-12-04 17:11 UTC, merged